# Generated by Django 4.2.20 on 2025-06-19 00:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('NONE', 'None'), ('DUMBBELL', 'Dumbbell'), ('BARBELL', 'Barbell'), ('MACHINE', 'Machine'), ('BODYWEIGHT', 'Bodyweight'), ('CABLE MACHINE', 'Cable Machine'), ('PLATE', 'Plate'), ('MEDICINE BALL', 'Medicine Ball'), ('OTHER', 'other')], max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('muscle_image', models.ImageField(blank=True, null=True, upload_to='muscle_images/')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_exercises', to=settings.AUTH_USER_MODEL)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_exercise', to='exercises.equipment')),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sets', models.PositiveIntegerField()),
                ('reps', models.PositiveIntegerField()),
                ('weight', models.FloatField(blank=True, null=True)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('distance', models.FloatField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercises.exercise')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('WEIGHT', 'Weight'), ('WEIGHT_REPS', 'Weight and Reps'), ('BODYWEIGHT_REPS', 'Bodyweight Reps'), ('WEIGHTED_BODYWEIGHT', 'Weighted Bodyweight'), ('ASSISTED_BODYWEIGHT', 'Assisted Bodyweight'), ('DURATION', 'Duration'), ('DISTANCE_DURATION', 'Distance and Duration'), ('WEIGHT_DISTANCE', 'Weight and Distance')], max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Muscle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('UPPER CHEST', 'Upper Chest'), ('LOWER CHEST', 'Lower Chest'), ('FRONT DELT', 'Front Delt'), ('MIDDLE DELT', 'Middle Delt'), ('REAR DELT', 'Rear Delt'), ('BICEPS', 'Biceps'), ('TRICEPS', 'Triceps'), ('FOREARMS', 'Forearms'), ('UPPER BACK', 'Upper Back'), ('LOWER BACK', 'Lower Back'), ('MIDDLE BACK', 'Middle Back'), ('LATS', 'Lats'), ('TRAPS', 'Traps'), ('ABDOMINALS', 'Abdominals'), ('OBLIQUES', 'Obliques'), ('QUADRICEPS', 'Quadriceps'), ('HAMSTRINGS', 'Hamstrings'), ('GLUTES', 'Glutes'), ('CALVES', 'Calves'), ('ABDUCTORS', 'Abductors'), ('ADDUCTORS', 'Adductors'), ('CARDIO', 'Cardio'), ('OTHER', 'Other')], max_length=50)),
                ('parent', models.CharField(choices=[('CORE', 'None'), ('ARMS', 'Arms'), ('BACK', 'Back'), ('CHEST', 'Chest'), ('LEGS', 'Legs'), ('SHOULDERS', 'Shoulders'), ('NECK', 'Neck'), ('CARDIO', 'other')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutHistorySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('workouts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_histories', to='exercises.exerciselog')),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_day', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('exercises', models.ManyToManyField(related_name='workout_days', to='exercises.exercise')),
            ],
        ),
        migrations.AddField(
            model_name='exerciselog',
            name='workout_day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercises.workoutday'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='exercise_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_exercise', to='exercises.exercisetype'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='main_muscle_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_exercises', to='exercises.muscle'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='primary_muscles',
            field=models.ManyToManyField(related_name='primary_exercises', to='exercises.muscle'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='secondary_muscles',
            field=models.ManyToManyField(related_name='secondary_exercises', to='exercises.muscle'),
        ),
    ]
