# Generated by Django 4.2.20 on 2025-06-25 17:27

from django.db import migrations

def add_muscles(apps, schema_editor):
    Muscle = apps.get_model('exercises', 'Muscle')

    MUSCLES = [
    {"name": "UPPER CHEST", "parent": "CHEST"},
    {"name": "LOWER CHEST", "parent": "CHEST"},
    {"name": "FRONT DELT", "parent": "SHOULDERS"},
    {"name": "MIDDLE DELT", "parent": "SHOULDERS"},
    {"name": "REAR DELT", "parent": "SHOULDERS"},
    {"name": "BICEPS", "parent": "ARMS"},
    {"name": "TRICEPS", "parent": "ARMS"},
    {"name": "FOREARMS", "parent": "ARMS"},
    {"name": "UPPER BACK", "parent": "BACK"},
    {"name": "LOWER BACK", "parent": "BACK"},
    {"name": "MIDDLE BACK", "parent": "BACK"},
    {"name": "LATS", "parent": "BACK"},
    {"name": "TRAPS", "parent": "BACK"},
    {"name": "ROTATOR CUFF", "parent": "SHOULDERS"},
    {"name": "ABDOMINALS", "parent": "CORE"},
    {"name": "OBLIQUES", "parent": "CORE"},
    {"name": "QUADRICEPS", "parent": "LEGS"},
    {"name": "HAMSTRINGS", "parent": "LEGS"},
    {"name": "GLUTES", "parent": "LEGS"},
    {"name": "CALVES", "parent": "LEGS"},
    {"name": "ABDUCTORS", "parent": "LEGS"},
    {"name": "ADDUCTORS", "parent": "LEGS"},
    {"name": "CARDIO", "parent": "CARDIO"},
    {"name": "OTHER", "parent": "OTHER"},
]

    for muscle in MUSCLES:
        Muscle.objects.get_or_create(name=muscle["name"], parent=muscle["parent"])

def delete_muscles(apps, schema_editor):
    Muscle = apps.get_model('exercises', 'Muscle')
    Muscle.objects.all().delete()

def add_exercise_types(apps, schema_editor):
    ExerciseType = apps.get_model('exercises', 'ExerciseType')

    CHOICES = [
        ('WEIGHT', 'Weight'),
        ('WEIGHT_REPS', 'Weight and Reps'),
        ('BODYWEIGHT_REPS', 'Bodyweight Reps'),
        ('WEIGHTED_BODYWEIGHT', 'Weighted Bodyweight'),
        ('ASSISTED_BODYWEIGHT', 'Assisted Bodyweight'),
        ('DURATION', 'Duration'),
        ('DISTANCE_DURATION', 'Distance and Duration'),
        ('WEIGHT_DISTANCE', 'Weight and Distance'),
    ]

    for choice, _ in CHOICES:
        ExerciseType.objects.get_or_create(name=choice)

def delete_exercise_types(apps, schema_editor):
    ExerciseType = apps.get_model('exercises', 'ExerciseType')
    ExerciseType.objects.all().delete()

def add_equipment(apps, schema_editor):
    Equipment = apps.get_model('exercises', 'Equipment')

    CHOICES = [
        ('NONE', 'None'),
        ('DUMBBELL', 'Dumbbell'),
        ('BARBELL', 'Barbell'),
        ('MACHINE', 'Machine'),
        ('BODYWEIGHT', 'Bodyweight'),
        ('CABLE MACHINE', 'Cable Machine'),
        ('PLATE', 'Plate'),
        ('MEDICINE BALL', 'Medicine Ball'),
        ('OTHER', 'other'),
    ]

    for choice, _ in CHOICES:
        Equipment.objects.get_or_create(name=choice)

def delete_equipment(apps, schema_editor):
    Equipment = apps.get_model('exercises', 'Equipment')
    Equipment.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_muscles, reverse_code=delete_muscles),
        migrations.RunPython(add_exercise_types, reverse_code=delete_exercise_types),
        migrations.RunPython(add_equipment, reverse_code=delete_equipment)
    ]
