# Generated by Django 4.2.20 on 2025-06-25 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0003_populate_exercises'),
    ]

    operations = [
        migrations.AlterField(
            model_name='muscle',
            name='parent',
            field=models.CharField(choices=[('CORE', 'Core'), ('ARMS', 'Arms'), ('BACK', 'Back'), ('CHEST', 'Chest'), ('LEGS', 'Legs'), ('SHOULDERS', 'Shoulders'), ('NECK', 'Neck'), ('CARDIO', 'Cardio'), ('OTHER', 'Other')], max_length=50),
        ),
    ]
