# Generated by Django 4.2.20 on 2025-06-27 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0004_alter_muscle_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exerciselog',
            name='distance',
        ),
        migrations.RemoveField(
            model_name='exerciselog',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='exerciselog',
            name='reps',
        ),
        migrations.RemoveField(
            model_name='exerciselog',
            name='sets',
        ),
        migrations.RemoveField(
            model_name='exerciselog',
            name='weight',
        ),
        migrations.CreateModel(
            name='SetLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_sets', models.PositiveIntegerField()),
                ('num_reps', models.PositiveIntegerField()),
                ('weight', models.FloatField(blank=True, null=True)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('distance', models.FloatField(blank=True, null=True)),
                ('exercise_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='exercises.exerciselog')),
            ],
        ),
    ]
