# Generated by Django 4.2.20 on 2025-06-27 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0005_remove_exerciselog_distance_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exerciselog',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='setlog',
            options={'ordering': ['exercise_log', 'set_num']},
        ),
        migrations.AlterModelOptions(
            name='workoutday',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='setlog',
            old_name='num_sets',
            new_name='set_num',
        ),
    ]
