# Generated by Django 4.2.20 on 2025-07-23 00:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0006_alter_exerciselog_options_alter_setlog_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exerciselog',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='setlog',
            name='distance',
            field=models.FloatField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='setlog',
            name='duration',
            field=models.DurationField(blank=True, default=datetime.timedelta(0)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='setlog',
            name='weight',
            field=models.FloatField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
