# Generated by Django 4.2.20 on 2025-07-23 00:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0007_alter_exerciselog_options_alter_setlog_distance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setlog',
            name='duration',
            field=models.DurationField(blank=True, default=datetime.timedelta(0)),
        ),
    ]
