# Generated by Django 4.2.20 on 2025-07-23 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0008_alter_setlog_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setlog',
            name='distance',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='setlog',
            name='num_reps',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='setlog',
            name='weight',
            field=models.FloatField(),
        ),
    ]
