# Generated by Django 4.2.20 on 2025-07-23 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0009_alter_setlog_distance_alter_setlog_num_reps_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setlog',
            name='distance',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='setlog',
            name='num_reps',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='setlog',
            name='weight',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
