# Generated by Django 5.2.6 on 2025-10-27 10:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0010_alter_setlog_distance_alter_setlog_num_reps_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_exercises', to='exercises.equipment'),
        ),
        migrations.AlterField(
            model_name='exerciselog',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='exercises.exercise'),
        ),
        migrations.AlterField(
            model_name='exerciselog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='exerciselog',
            name='workout_day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_logs', to='exercises.workoutday'),
        ),
        migrations.AlterField(
            model_name='workoutday',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_days', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='workouthistorysnapshot',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_history', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='workouthistorysnapshot',
            name='workouts',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_history', to='exercises.exerciselog'),
        ),
    ]
