# Generated by Django 5.2.6 on 2025-10-27 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0011_alter_exercise_equipment_alter_exerciselog_exercise_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WorkoutHistorySnapshot',
        ),
    ]
